# Defines the design of the whole page
# Possible values: [FIN, OvGU]
design: OvGU

menu:
  legals: true
  courses: true
  news: true
  programs: true
  downloads: true

administration:
  send_new_user_registered_notification: true

mail:
  from: "no-reply@anywhere.com"
  smtp:
    server_address: "mail.anywhere.com"
    port: 587
    user_name: "user"
    password: "myOwnSecret"

  #All Mails are getting bypassed to this adress while in devolpment Mode
  development_bypass_target: "nobody@example.com"

